#ifndef COMMON_H
#define COMMON_H
#include <string>
#include <stdio.h>
#include <vector>
#include "rapidjson/document.h"
#include "rapidjson/filereadstream.h"
#include <iostream>
#include <algorithm>
#include "glm/glm.hpp"
#include <unordered_set>
#include <SDL2/include/SDL.h>
#include <SDL2/include/SDL_image.h>
#include <SDL2/include/SDL_ttf.h>
#include <SDL2/include/SDL_mixer.h>
#include <string>
#include <optional>
#include "../libs/lua-5.4.6/src/lua.hpp"
#include "../libs/LuaBridge-2.8/Source/LuaBridge/LuaBridge.h"
#include <filesystem>
#include "Component.h"
#include <thread>
#include <chrono>
#include <queue>
#include "../libs/box2d-2.4.1/include/box2d/box2d.h"
#endif // COMMON_H
